---
name: Feature Request
description: Propose a new idea or feature
labels: ["feature"]
body:
- type: textarea
  attributes:
    label: Describe your request
    placeholder: |
      Foo should be able to do bar and baz.
  validations:
    required: true
- type: textarea
  attributes:
    label: Briefly explain its use-case
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      **Thank you for taking the time to fill out a feature request!**
